### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by jamestewartjr** [jamestewartjr/renotify#3]
Tools to add to CI
- [ ]  QA branch
- [x]  Jest testing
- [x]  Cypress testing:  https://docs.cypress.io/guides/guides/continuous-integration.html#Boot-your-server

**Comment by jamestewartjr** [comment]
https://circleci.com/sunset1-0/

**Comment by jamestewartjr** [comment]
Example config.yml file:
```
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
```
